import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import Main from '@/components/Main';

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio 2023</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  );
}
